# Generated by Django 5.2.4 on 2025-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Father Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, verbose_name='Gender')),
                ('tazkira_number', models.CharField(max_length=50, unique=True, verbose_name='Tazkira Number')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=8, null=True, verbose_name='Marital Status')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Blood Group')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('village', models.CharField(blank=True, max_length=100, null=True, verbose_name='Village')),
                ('address_details', models.TextField(blank=True, null=True, verbose_name='Address Details')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
